export enum ShortName {
    ResourceName = 'rn',
    Type = 'ty',
    ResourceID = 'ri',
    CreationTime = 'ct',
    LastModifiedTime = 'lt',
    ExpirationTime = 'et',
    ContentFormat = 'cnf',
    Content = 'con',
    ParentId = 'pi',
    ContainerName = 'cn',
    ContentInstance = 'cin',
    ApplicationEntity = 'ae',
    FilterUsage = 'fu',
    ResultContent = 'rcn',
}
